<br>
<h1 style = "font-size:40px; font-family:monospace ; font-weight : bold; color : #3C0096; text-align: center;
border-radius: 5px 25px;">Grades Prediction with Machine Learning</h1>
<br>

<span style="font-size:20px;color:#00033E;font-weight : bold">

By using machine learning algorithms, we can predict how well the students are going to perform so that we can help the students whose grades are predicted low.Grades Prediction is based on the linear regression problem  </span>

<span style="font-size:20px;color:#0026D8;font-weight : bold">Dataset Description:</span>


**This dataset contains student achievement in secondary education of two Portuguese schools.**
- **school** - student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)<br>
- **sex** - student's sex (binary: 'F' - female or 'M' - male)<br>
- **age** - student's age (numeric: from 15 to 22)<br>
- **address** - student's home address type (binary: 'U' - urban or 'R' - rural)<br>
- **famsize** - family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)<br>
- **Pstatus** - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)<br>
- **Medu** - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)<br>
- **Fedu** - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)<br>
- **Mjob** - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')<br>
- **Fjob** - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')<br>
- **reason** - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')<br>
- **guardian** - student's guardian (nominal: 'mother', 'father' or 'other')
- **traveltime** - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)<br>
- **studytime** - weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)<br>
- **failures** - number of past class failures (numeric: n if 1<=n<3, else 4)<br>
- **schoolsup** - extra educational support (binary: yes or no)<br>
- **famsup** - family educational support (binary: yes or no)<br>
- **paid** - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)<br>
- **activities** - extra-curricular activities (binary: yes or no)<br>
- **nursery** - attended nursery school (binary: yes or no)<br>
- **higher** - wants to take higher education (binary: yes or no)<br>
- **internet** - Internet access at home (binary: yes or no)<br>
- **romantic** - with a romantic relationship (binary: yes or no)<br>
- **famrel** - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)<br>
- **freetime** - free time after school (numeric: from 1 - very low to 5 - very high)<br>
- **goout** - going out with friends (numeric: from 1 - very low to 5 - very high)<br>
- **Dalc** - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)<br>
- **Walc** - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)<br>
- **health** - current health status (numeric: from 1 - very bad to 5 - very good)<br>
- **absences** - number of school absences (numeric: from 0 to 93)<br>

<span style="font-size:20px;color:#0026D8;font-weight : bold">these grades are related with the course subject, Math or Portuguese:</span>

- **G1** - first period grade (numeric: from 0 to 20)<br>
- **G2** - second period grade (numeric: from 0 to 20)<br>
- **G3** - final grade (numeric: from 0 to 20, output target)<br>


<h1 style="background-color:#ABFF9B;font-size:20px;color:#00033E;font-weight : bold">✅ Importing Required Libraries</h1>

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle


data = pd.read_csv("dataset for grade prediction.csv")
data.describe()    # Dataset description

age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

<h1 style="background-color:#ABFF9B;font-size:20px;color:#00033E;font-weight : bold">✅ To check any null values present in dataset</h1>

In [2]:
data.isnull().any()   

school        False
sex           False
age           False
address       False
famsize       False
Pstatus       False
Medu          False
Fedu          False
Mjob          False
Fjob          False
reason        False
guardian      False
traveltime    False
studytime     False
failures      False
schoolsup     False
famsup        False
paid          False
activities    False
nursery       False
higher        False
internet      False
romantic      False
famrel        False
freetime      False
goout         False
Dalc          False
Walc          False
health        False
absences      False
G1            False
G2            False
G3            False
dtype: bool

<h1 style="background-color:#ABFF9B;font-size:20px;color:#00033E;font-weight : bold">✅Prepare the data  and process using Linear Regression </h1>

**The G3 column is target label, split the dataset into 20% testing and 80% training.** 


In [11]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)


0.863006795021235


<h1 style="background-color:#ABFF9B;font-size:20px;color:#00033E;font-weight : bold"> ✅Accuracy score for LR :</h1> 

In [15]:
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.863006795021235


<h1 style="background-color:#ABFF9B;font-size:20px;color:#00033E;font-weight : bold">✅ predictions by the  model:</h1> 



In [16]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 3.09218296 13.31666438 12.96004141  6.98967512 13.31666438]
 [ 3.09218296  3.09218296 12.96004141  6.98967512 11.64608269]
 [15.18072367  9.83426804 12.96004141 11.30431805 12.81481061]
 ...
 [12.81481061  9.83426804  8.44536157 11.30431805 11.30431805]
 [13.34437267 18.6314878   8.44536157  6.98967512  6.98967512]
 [ 9.83426804 13.86802949  8.44536157  6.98967512  3.09218296]] [[[ 7  4  1  2  0]
  [13 13  2  0 14]
  [12 13  1  1  6]
  [ 8  8  4  0 10]
  [13 13  2  0 14]]

 [[ 7  4  1  2  0]
  [ 7  4  1  2  0]
  [12 13  1  1  6]
  [ 8  8  4  0 10]
  [14 12  4  0  6]]

 [[15 15  2  0  4]
  [12 10  3  0 10]
  [12 13  1  1  6]
  [ 8 12  1  0  0]
  [10 13  1  0  6]]

 ...

 [[10 13  1  0  6]
  [12 10  3  0 10]
  [ 9  9  2  0  4]
  [ 8 12  1  0  0]
  [ 8 12  1  0  0]]

 [[12 14  3  0  1]
  [19 18  2  0  2]
  [ 9  9  2  0  4]
  [ 8  8  4  0 10]
  [ 8  8  4  0 10]]

 [[12 10  3  0 10]
  [12 14  1  0  0]
  [ 9  9  2  0  4]
  [ 8  8  4  0 10]
  [ 7  4  1  2  0]]] [array([[ 0, 14, 14,  8, 14]

       [12, 15, 10,  8,  0]])]
[[ 3.09218296 13.31666438 12.96004141  6.98967512 13.31666438]
 [ 3.09218296  3.09218296 12.96004141  6.98967512 11.64608269]
 [15.18072367  9.83426804 12.96004141 11.30431805 12.81481061]
 ...
 [12.81481061  9.83426804  8.44536157 11.30431805 11.30431805]
 [13.34437267 18.6314878   8.44536157  6.98967512  6.98967512]
 [ 9.83426804 13.86802949  8.44536157  6.98967512  3.09218296]] [[[ 7  4  1  2  0]
  [13 13  2  0 14]
  [12 13  1  1  6]
  [ 8  8  4  0 10]
  [13 13  2  0 14]]

 [[ 7  4  1  2  0]
  [ 7  4  1  2  0]
  [12 13  1  1  6]
  [ 8  8  4  0 10]
  [14 12  4  0  6]]

 [[15 15  2  0  4]
  [12 10  3  0 10]
  [12 13  1  1  6]
  [ 8 12  1  0  0]
  [10 13  1  0  6]]

 ...

 [[10 13  1  0  6]
  [12 10  3  0 10]
  [ 9  9  2  0  4]
  [ 8 12  1  0  0]
  [ 8 12  1  0  0]]

 [[12 14  3  0  1]
  [19 18  2  0  2]
  [ 9  9  2  0  4]
  [ 8  8  4  0 10]
  [ 8  8  4  0 10]]

 [[12 10  3  0 10]
  [12 14  1  0  0]
  [ 9  9  2  0  4]
  [ 8  8  4  0 10]
  [ 7  4  1  2  0]